services:
  - type: web
    name: api-security-lab
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGIN
        value: "https://client-mu-ashen-58.vercel.app"
      - key: NODE_ENV
        value: production
